### ISSUE TITLE
About the training functions

### ISSUE THREAD

**Issue by lzlzlizi** [tsujuifu/pytorch_sscr#2]
Hi, 

Can you give us a little bit description of the differences between`train_ctr(), train_with_ctr(), train()`.

Is `train_with_ctr()` the implementation of your sscr methods? 

Thanks.

**Comment by tsujuifu** [comment]
Hi lzlzlizi, 

**train()**: train the baseline GeNeVA (G)
**train_ctr()**: train the iterative explainer (E)
**train_with_ctr()**: train G w/ E (CTC)

You can edit dataset.py (ex: [clevr_dataset.py](https://github.com/tsujuifu/pytorch_sscr/blob/master/sscr/geneva/data/clevr_dataset.py))
to replace the token in the instruction to do SSCR

**Comment by lzlzlizi** [comment]
Hi @tsujuifu,

Thanks for the fast reply. I am a little bit confused. So what you mean is that there is no function in the repository to directly replicate your results, and we need to modify the dataset.py to do the sscr, right?

Could you please give us a short description about how to replicate your sscr model in your paper? For example, which train function to use,  more detailed codes for data generation, how to combine them together to train, and the hyper-parameters to use if they are not the same with the example_args?

Thanks.

**Comment by tsujuifu** [comment]
Hi @lzlzlizi,

1. run **train()** to train base G
2. run **train_ctr()** to pre-train E
3. run **train_with_ctr()** to do CTC (train G w/ E)

And I will clean and upload **dataset.py** for SSCR later (maybe after CVPR since I am quite busy these days).

If you want to do further experiments, you can first take the pre-trained snapshots [here](https://drive.google.com/drive/u/1/folders/1DvmEmqTaDjZA0Fea1MfW7A0Kz2fjf8g9).

**Comment by lzlzlizi** [comment]
Ok, thanks!
